#!/bin/sh
set -e
CFG_PATH=""
if [ -e /sys/firmware/efi/efivars ]; then
	CFG_PATH="/boot/efi/grub.cfg"
else
	CFG_PATH="/boot/grub/grub.cfg"
fi
grub-mkconfig -o "$CFG_PATH" "$@"

# sign config
GPG_KEY=/root/setup-scripts/gpg-key

sign(){
	if [ -f $GPG_KEY ]; then
		rm -rf "$1".sig
		gpg --default-key "$(cat $GPG_KEY)" --detach-sign "$1"
		echo "Signing $1..."
	else
		echo "Not GPG key, not signing $1..."
	fi
}

sign "$CFG_PATH"
