#!/bin/sh
set -e
grub-mkconfig -o /boot/grub/grub.cfg "$@"
# sign config
GPG_KEY=/root/setup-scripts/gpg-key

sign(){
	rm -rf "$1".sig
	gpg --default-key "$(cat $GPG_KEY)" --detach-sign "$1"
	echo "Signing $1..."
}

sign /boot/grub/grub.cfg
